// demo-snippets/vue/StaticPager.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Static Pager" />
        </ActionBar>

        <StackLayout class="page">
            <Pager height="100%">
                <PagerItem backgroundColor="#e67e22"><Label text="First" /></PagerItem>
                <PagerItem backgroundColor="#3498db"><Label text="Second" /></PagerItem>
                <PagerItem backgroundColor="#e74c3c"><Label text="Third" /></PagerItem>
                <PagerItem backgroundColor="#9b59b6"><Label text="Fourth" /></PagerItem>
            </Pager>
        </StackLayout>
    </Page>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped>

.page Label {
    font-size: 35;
    horizontal-alignment: center;
    vertical-alignment: center;
    color: #ffffff;
    text-transform: uppercase;
}

</style>

// demo-snippets/ng/static-pager/static-pager.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from '@nativescript/angular';

@Component({
    selector: 'ns-static-pager',
    templateUrl: './static-pager.component.html',
    styleUrls: ["./static-pager.component.scss"],
})
export class StaticPagerComponent implements OnInit {
    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {}

    goBack(): void {
        this.router.back();
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Static Pager"></Label>
</ActionBar>

<StackLayout>
    <Pager height="100%">
        <GridLayout *pagerItem backgroundColor="#e67e22">
            <Label text="First" class="label"></Label>
        </GridLayout>
        <GridLayout *pagerItem backgroundColor="#3498db">
            <Label text="Second" class="label"></Label>
        </GridLayout>
        <GridLayout *pagerItem backgroundColor="#e74c3c">
            <Label text="Third" class="label"></Label>
        </GridLayout>
        <GridLayout *pagerItem backgroundColor="#9b59b6">
            <Label text="Fourth" class="label"></Label>
        </GridLayout>
    </Pager>
</StackLayout>
