// demo-snippets/react/Indicator.tsx
import * as React from 'react';
import { Pager } from '@nativescript-community/ui-pager/react';

const items = [
    {title: "First", color: "#e67e22"},
    {title: "Second", color: "#3498db"},
    {title: "Third", color: "#e74c3c"},
    {title: "Fourth", color: "#9b59b6"},
];

interface Item {
    title: string;
    color: string;
}

const cellFactory = (item: Item) => (
    <gridLayout backgroundColor={item.color} height={{ unit: "%", value: 100 }}>
        <label 
            //@ts-ignore
            width="100%"
            text={item.title} 
            textAlignment={"center"} 
            verticalAlignment={"middle"}
            fontSize={35}
            textTransform={"uppercase"}
            color={"white"} />
    </gridLayout>
);

export function Indicator() {
    return (
        <stackLayout>
            <Pager
                height={{ unit: "dip", value: 300 }}
                items={items}
                indicator="fill"
                showIndicator={true}
                cellFactory={cellFactory} />
        </stackLayout>
    );
}

// demo-snippets/svelte/Indicator.svelte
<script lang="ts">
    import { goBack } from 'svelte-native';
    import { Template } from 'svelte-native/components';

    const items = [
        { title: 'First', color: '#e67e22' },
        { title: 'Second', color: '#3498db' },
        { title: 'Third', color: '#e74c3c' },
        { title: 'Fourth', color: '#9b59b6' }
    ];
</script>

<page>
    <actionBar title="Indicator">
        <navigationButton text="Go back" on:tap={() => goBack()} />
    </actionBar>
    <stackLayout class="page">
        <pager {items} height="300" indicator="fill" showIndicator="true">
            <Template let:item>
                <gridlayout backgroundColor={item.color}>
                    <label class="label" text={item.title} />
                </gridlayout>
            </Template>
        </pager>
    </stackLayout>
</page>

<style>
    .label {
        font-size: 35;
        width: 100%;
        text-align: center;
        vertical-alignment: center;
        color: #ffffff;
        text-transform: uppercase;
    }
</style>
