// demo-snippets/ng/indicator/indicator.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from '@nativescript/angular';

@Component({
    selector: 'ns-indicator',
    templateUrl: './indicator.component.html',
    styleUrls: ["./indicator.component.scss"],
})
export class IndicatorComponent implements OnInit {
    selectedIndex = 0;

    constructor(private router: RouterExtensions) {}

    items = [
        {
            title: "First",
            color: "#e67e22"
        },
        {
            title: "Second",
            color: "#3498db"
        },
        {
            title: "Third",
            color: "#e74c3c"
        },
        {
            title: "Fourth",
            color: "#9b59b6"
        }
    ];

    ngOnInit(): void {}

    goBack(): void {
        this.router.back();
    }
    resetPager() {
        this.selectedIndex = 0;
    }
    onIndexChanged(event: any): void {
        this.selectedIndex = event.value;
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Indicator"></Label>
</ActionBar>

<StackLayout>
    <Pager
        [items]="items"
        height="300"
        [selectedIndex]="selectedIndex"
        (selectedIndexChange)="onIndexChanged($event)"
        indicator="fill"
        showIndicator="true"
    >
        <ng-template let-i="index" let-item="item">
            <GridLayout
                [backgroundColor]="item.color"
            >
                <Label class="label" [text]="item.title"></Label>
            </GridLayout>
        </ng-template>
    </Pager>
    <Button text="Reset" (tap)="resetPager()"></Button>
</StackLayout>

// demo-snippets/vue/Indicator.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Indicator" />
        </ActionBar>

        <StackLayout class="page">
            <Pager ref="pager" for="item in items" :selectedIndex="selectedIndex" @selectedIndexChange="selectedIndexChange" height="300" indicator="fill" showIndicator="true">
                <v-template>
                    <GridLayout :backgroundColor="item.color">
                        <Label :text="item.title" />
                    </GridLayout>
                </v-template>
            </Pager>
            <Button text="Reset" @tap="resetPager" />
        </StackLayout>
    </Page>
</template>

<script>

export default {
    data() {
        return {
            selectedIndex: 2,
            items: [
                {title: 'First', color: '#e67e22'},
                {title: 'Second', color: '#3498db'},
                {title: 'Third', color: '#e74c3c'},
                {title: 'Fourth', color: '#9b59b6'},
            ]
        };
    },
    methods: {
        resetPager() {
            this.selectedIndex = 0;
        },
        selectedIndexChange(args) {
            console.log("SELECTED INDEX CHANGES", args.value)
            this.selectedIndex = args.value;
        }
    }
};
</script>

<style lang="scss" scoped>
.page Label {
    font-size: 35;
    text-align: center;
    width: 100%;
    vertical-alignment: center;
    color: #ffffff;
    text-transform: uppercase;
}
</style>
